name: CI

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main, UPSTREAM_WORKSPACE: 'github:ros-planning/navigation2#main -nav2_system_tests'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
